### ISSUE TITLE
TS2307: Cannot find module react-transition-progress or its corresponding type declarations.

### ISSUE THREAD

**Issue by gregorybolkenstijn** [vercel/react-transition-progress#5]
I have a Typescript project and when importing anything from `'react-transition-progress'`, I get this error:

`TS2307: Cannot find module react-transition-progress or its corresponding type declarations.
There are types at [...]/node_modules/react-transition-progress/dist/es/index.d.mts, but this result could not be resolved under your current moduleResolution setting. Consider updating to node16, nodenext, or bundler`

I followed the suggested changes to `tsconfig.json` for `moduleResolution`, but that led to more issues. I could not find a new configuration that did not trigger new issues. We've never encountered this issue with other packages in our project, any advice on how to solve this would be great. I've added a `@ts-expect-error` to now as the code works fine.

**Comment by timneutkens** [comment]
I'd love to give advice but this issue does not include a reproduction, can you add one? The included example application runs fine with TypeScript.

**Comment by timneutkens** [comment]
Closing as no reproduction was provided.

**Comment by mkmule** [comment]
Update your `tsconfig.json`, it worked for me.

```
from
    "moduleResolution": "node",
to
    "moduleResolution": "bundler",
```
