### ISSUE TITLE
Add support for UrlObject

### ISSUE THREAD

**Issue by korsvanloon** [vercel/react-transition-progress#8]
The next/link object can have a regular object as href, but the react-transition-progress link calls toString on the href resulting in [Object object].
It needs the format function from the url library instead:

```ts
import { format } from "url";

const hrefString = typeof href === "string" ? href : format(href)
```

**Comment by timneutkens** [comment]
Feel free to send a PR.

**Comment by korsvanloon** [comment]
here you go :)
added in an extra fix for scroll behaviour

**Comment by korsvanloon** [comment]
@timneutkens Could you please have a look at my PR? And trigger another release?
The CMD+click fix would also be great to have released.
